spring.application.name=backend_EAV
spring.datasource.url=jdbc:postgresql://localhost:5432/EAVMapsOfKaindorf
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=create