# -------------------------------
# Spring Boot Anwendung
# -------------------------------
spring.application.name=backend

# -------------------------------
# Server Konfiguration
# -------------------------------
server.port=8080

# -------------------------------
# MongoDB Atlas Verbindung
# -------------------------------
spring.data.mongodb.uri=mongodb+srv://francaluise2_db_user:iTugYmWDQiqahXAJ@mapsofkaindorf.44ch8hx.mongodb.net/mapsOfKaindorf?retryWrites=true&w=majority

# -------------------------------
# Logging
# -------------------------------
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.web=INFO

# JSON pretty print
spring.jackson.serialization.indent_output=true