# -------------------------------
# Spring Boot Anwendung
# -------------------------------
spring.application.name=backend

# -------------------------------
# Server Konfiguration
# -------------------------------
server.port=8082

application.security.jwt.secret=GX5dfu9C5daaOeXXlgP1z3miHUYJq3rPQwVCIPDWmZ6
application.security.jwt.expiration=86400000
application.security.jwt-refresh.expiration=7

# -------------------------------
# MongoDB Atlas Verbindung
# -------------------------------
#PROD: spring.data.mongodb.uri=mongodb+srv://franca:<password>@mapsofkaindorf.44ch8hx.mongodb.net/mapsOfKaindorf
#DEV:  mongodb://localhost:27017/mapsOfKaindorf

# -----------------
# -----------
# Logging
# -------------------------------
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.web=INFO

# JSON pretty print
spring.jackson.serialization.indent_output=true

spring.profiles.active=dev